---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: dev-cluster-addons.ti.com.0.0.1
spec:
  refName: dev-cluster-addons.ti.com
  version: 0.0.1
  releaseNotes: |
        Initial release of the dev-cluster-addons package that includes contour
  releasedAt: 2023-01-16T04:45:00Z
  valuesSchema:
    openAPIv3:
      title: gitea.vmware.com values schema
      examples:
      - ingress_domain: shared.azure.grogscave.net
        ingress_secret: default/default-cert-tls
      properties:
        ingress_domain:
          type: string
          description: Top level ingress domain for cluster.  Will prepend "gitea" to the domain for ingress.
          examples:
          - shared.azure.grogscave.net
        ingress_secret:
          type: string
          description: Name of TLS secret to use with HTTPProxy.  Can be a delgated secret from another namespace.
          examples:
          - my-tls-secret
          - default/default-cert-tls
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/cdelashmutt-pivotal/dev-cluster-addons
          ref: origin/main
          lfsSkipSmudge: true
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}