---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: dev-cluster-addons.ti.com.0.0.1
spec:
  refName: dev-cluster-addons.ti.com
  version: 0.0.1
  releaseNotes: |
        Initial release of the dev-cluster-addons package that includes fluent-bit
  releasedAt: 2023-01-16T04:45:00Z
  valuesSchema:
    openAPIv3:
      title: Dev Cluster Addons values schema
      examples:
      - cluster_name: my-cluster
      properties:
        cluster_name:
          type: string
          description: The name of the cluster you are installing to.
          default: UNKNOWN
          examples:
          - my-cluster
          - susan-dev-cluster
          - ncc-1701
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/cdelashmutt-pivotal/dev-cluster-addons.ti.com:0.0.1
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}