---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: dev-cluster-addons.ti.com.0.0.1
spec:
  refName: dev-cluster-addons.ti.com
  version: 0.0.1
  releaseNotes: |
        Initial release of the dev-cluster-addons package that includes contour
  releasedAt: 2023-01-16T04:45:00Z
  valuesSchema:
    openAPIv3:
      title: Dev Cluster Addons values schema
      examples:
      - special_setting: foo
      properties:
        special_setting:
          type: string
          description: A special setting that you want to expose to the teams installing this package
          examples:
          - foo
          - bar
          - foobar
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/cdelashmutt-pivotal/dev-cluster-addons.ti.com:0.0.1
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}