---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: ti-package-repo
spec:
  syncPeriod: 1m
  fetch:
    imgpkgBundle:
      image: ghcr.io/cdelashmutt-pivotal/ti-package-repo:0.0.1